version: '3'
services:
  backend:
    image: qnib/plain-elasticsearch:5.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 768M
    environment:
      ES_HEAP_MAX: "512m"
      ES_HEAP_MIN: "512m"
      ES_NODE_MASTER: "true"
      ES_NODE_DATA: "true"
  frontend:
    image: qnib/plain-kibana5:5.5.1
    ports:
      - "5601:5601"
    environment:
        ES_MASTER_HOST: tasks.backend
